return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = {
      flavour = "frappe",
      background = { light = "latte", dark = "frappe" },
      transparent_background = false,

      color_overrides = {
        frappe = {
          base = "#060608",
          mantle = "#040406",
          crust = "#020203",
        },
      },

      highlight_overrides = {
        frappe = function(_)
          local D = {
            fg = "#A9B7C6",
            keyword = "#CC7832",
            func = "#FFC66D",
            field = "#9876AA",
            string = "#6A8759",
            number = "#6897BB",
            comment = "#808080",
            doccomment = "#629755",
            preproc = "#BBB529",
            macro = "#908B25",
            namespace = "#B5B6E3",
            typedef = "#B9BCD1",
            special_comment = "#8A653B",
          }

          return {
            -- ── BASE VIM SYNTAX GROUPS ─────────────────────────────────────
            Normal = { fg = D.fg },
            Comment = { fg = D.comment, style = { "italic" } },
            Keyword = { fg = D.keyword, style = { "bold" } },
            Statement = { fg = D.keyword, style = { "bold" } },
            Conditional = { fg = D.keyword, style = { "bold" } },
            Repeat = { fg = D.keyword, style = { "bold" } },
            Exception = { fg = D.keyword, style = { "bold" } },
            StorageClass = { fg = D.keyword, style = { "bold" } },
            Structure = { fg = D.keyword, style = { "bold" } },
            Boolean = { fg = D.keyword, style = { "bold" } },
            Function = { fg = D.func },
            String = { fg = D.string },
            Character = { fg = D.string },
            Number = { fg = D.number },
            Float = { fg = D.number },
            Constant = { fg = D.field, style = { "italic" } },
            Identifier = { fg = D.fg },
            Type = { fg = D.fg },
            Typedef = { fg = D.typedef },
            Operator = { fg = D.fg },
            Delimiter = { fg = D.keyword },
            PreProc = { fg = D.preproc },
            Include = { fg = D.preproc },
            Define = { fg = D.preproc },
            Macro = { fg = D.macro },
            PreCondit = { fg = D.preproc },
            Special = { fg = D.preproc },
            SpecialChar = { fg = D.keyword, style = { "bold" } },
            SpecialComment = { fg = D.special_comment, style = { "italic" } },
            Tag = { fg = D.keyword },
            Debug = { fg = "#666D75", style = { "italic" } },
            Todo = { fg = "#A8C023", style = { "italic" } },
            Underlined = { fg = D.fg, style = { "underline" } },

            -- ── C/C++ VIM SYNTAX GROUPS ────────────────────────────────────
            cMacroName = { fg = D.macro },
            cSomeMacro = { fg = D.macro },
            cConstant = { fg = D.macro },
            cPreInclude = { fg = D.string },
            cPreProcRegion = { fg = D.fg },
            cDataStructure = { fg = D.namespace },
            cDataStructureKeyword = { fg = D.keyword, style = { "bold" } },
            cFunction = { fg = D.func },
            cppDestructor = { fg = D.func },
            cStructField = { fg = D.field },
            cppAfterColon = { fg = D.field },
            cppBeforeColon = { fg = D.namespace },
            cppNullptr = { fg = D.keyword, style = { "bold" } },
            cppTemplate = { fg = D.keyword, style = { "bold" } },
            cTypedef = { fg = D.keyword, style = { "bold" } },
            cppTypeName = { fg = D.keyword, style = { "bold" } },
            cEnum = { fg = D.keyword, style = { "bold" } },
            cSpecial = { fg = D.keyword, style = { "bold" } },
            cUserLabel = { fg = D.fg },

            -- ── TREE-SITTER GROUPS ─────────────────────────────────────────
            ["@keyword"] = { fg = D.keyword, style = { "bold" } },
            ["@keyword.function"] = { fg = D.keyword, style = { "bold" } },
            ["@keyword.operator"] = { fg = D.keyword, style = { "bold" } },
            ["@keyword.return"] = { fg = D.keyword, style = { "bold" } },
            ["@keyword.type"] = { fg = D.keyword, style = { "bold" } },
            ["@keyword.modifier"] = { fg = D.keyword, style = { "bold" } },
            ["@keyword.repeat"] = { fg = D.keyword, style = { "bold" } },
            ["@keyword.conditional"] = { fg = D.keyword, style = { "bold" } },
            ["@keyword.exception"] = { fg = D.keyword, style = { "bold" } },
            ["@keyword.import"] = { fg = D.preproc },
            ["@keyword.directive"] = { fg = D.preproc },
            ["@keyword.directive.define"] = { fg = D.preproc },
            ["@keyword.storage"] = { fg = D.keyword, style = { "bold" } },
            ["@function"] = { fg = D.func },
            ["@function.call"] = { fg = D.fg },
            ["@function.method"] = { fg = D.func },
            ["@function.method.call"] = { fg = D.fg },
            ["@function.macro"] = { fg = D.macro },
            ["@constructor"] = { fg = D.func },
            ["@variable"] = { fg = D.fg },
            ["@variable.builtin"] = { fg = D.keyword, style = { "bold" } },
            ["@variable.member"] = { fg = D.field },
            ["@variable.parameter"] = { fg = D.fg },
            ["@type"] = { fg = D.fg },
            ["@type.builtin"] = { fg = D.keyword, style = { "bold" } },
            ["@type.definition"] = { fg = D.typedef },
            ["@constant"] = { fg = D.field, style = { "italic" } },
            ["@constant.builtin"] = { fg = D.keyword, style = { "bold" } },
            ["@constant.macro"] = { fg = D.macro },
            ["@module"] = { fg = D.namespace },
            ["@namespace"] = { fg = D.namespace },
            ["@comment"] = { fg = D.comment, style = { "italic" } },
            ["@comment.documentation"] = { fg = D.doccomment, style = { "italic" } },
            ["@string"] = { fg = D.string },
            ["@string.escape"] = { fg = D.keyword, style = { "bold" } },
            ["@string.special"] = { fg = D.keyword },
            ["@character"] = { fg = D.string },
            ["@number"] = { fg = D.number },
            ["@number.float"] = { fg = D.number },
            ["@boolean"] = { fg = D.keyword, style = { "bold" } },
            ["@operator"] = { fg = D.fg },
            ["@punctuation.bracket"] = { fg = D.fg },
            ["@punctuation.delimiter"] = { fg = D.fg },
            ["@punctuation.special"] = { fg = D.keyword, style = { "bold" } },
            ["@preproc"] = { fg = D.preproc },
            ["@define"] = { fg = D.preproc },

            -- ── LSP SEMANTIC TOKEN GROUPS (clangd) ────────────────────────
            ["@lsp.type.variable.cpp"] = { fg = D.fg },
            ["@lsp.type.parameter.cpp"] = { fg = D.fg },
            ["@lsp.type.function.cpp"] = { fg = D.func },
            ["@lsp.type.method.cpp"] = { fg = D.func },
            ["@lsp.type.property.cpp"] = { fg = D.field },
            ["@lsp.type.class.cpp"] = { fg = D.namespace },
            ["@lsp.type.struct.cpp"] = { fg = D.namespace },
            ["@lsp.type.type.cpp"] = { fg = D.fg },
            ["@lsp.type.typeParameter.cpp"] = { fg = D.fg },
            ["@lsp.type.namespace.cpp"] = { fg = D.namespace },
            ["@lsp.type.enum.cpp"] = { fg = D.keyword, style = { "bold" } },
            ["@lsp.type.enumMember.cpp"] = { fg = D.field, style = { "italic" } },
            ["@lsp.type.macro.cpp"] = { fg = D.macro },
            ["@lsp.type.concept.cpp"] = { fg = D.namespace },
            ["@lsp.type.operator.cpp"] = { fg = D.fg },
            ["@lsp.type.comment.cpp"] = { fg = D.comment, style = { "italic" } },
            ["@lsp.type.label.cpp"] = { fg = D.fg },
            ["@lsp.type.bracket.cpp"] = { fg = D.fg },
            ["@lsp.typemod.variable.classScope.cpp"] = { fg = D.field },
            ["@lsp.typemod.variable.static.cpp"] = { fg = D.field, style = { "italic" } },
            ["@lsp.typemod.variable.readonly.cpp"] = { fg = D.field, style = { "italic" } },
            ["@lsp.typemod.variable.globalScope.cpp"] = { fg = D.fg },
            ["@lsp.typemod.variable.functionScope.cpp"] = { fg = D.fg },
            ["@lsp.typemod.variable.namespaceScope.cpp"] = { fg = D.fg },
            ["@lsp.typemod.type.defaultLibrary.cpp"] = { fg = D.keyword, style = { "bold" } },
            ["@lsp.typemod.class.defaultLibrary.cpp"] = { fg = D.namespace },
            ["@lsp.typemod.function.defaultLibrary.cpp"] = { fg = D.func },
            ["@lsp.typemod.method.defaultLibrary.cpp"] = { fg = D.func },
            ["@lsp.typemod.method.static.cpp"] = { fg = D.func },
            ["@lsp.typemod.function.static.cpp"] = { fg = D.func },
            ["@lsp.typemod.variable.deprecated.cpp"] = { fg = D.fg, style = { "strikethrough" } },
            ["@lsp.typemod.function.deprecated.cpp"] = { fg = D.func, style = { "strikethrough" } },
            ["@lsp.typemod.method.deprecated.cpp"] = { fg = D.func, style = { "strikethrough" } },
            ["@lsp.typemod.variable.constructorOrDestructor.cpp"] = { fg = D.func },
            LspInlayHint = { fg = "#606366", style = { "italic" } },
          }
        end,
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin-frappe",
    },
  },
}
